### PR TITLE
chore: fix linting issues to allow upgrade to super-linterv6

### PR DESCRIPTION
**Pull request by jmeridth**
Closes #19 

# Pull Request

## Proposed Changes

- [x] add skips for checkov
  - can't add user due to needing root access [context](https://github.com/github/stale-repos/pull/103)
  - add health check endpoint - not there yet
- [x] move flake8 arguments from Makefile into .github/linters/.flake8 config file
  - use .flake8 config in Makefile
- [x] move .pylintrc from root to .github/linters/.pylintrc so superlinter uses it
  - rename file to .python-lint (default that superlinter looks for)
- [x] add missing --- at top of stale.yml github action (makes warning happy)
- [x] update super-linter to v6
- [x] update README with permissions best practices in examples

Fixes based on the following errors:

- [Checkov](https://github.com/github/cleanowners/actions/runs/8300093011/job/22717240878?pr=19#step:4:478)
- [pylint](https://github.com/github/cleanowners/actions/runs/8300093011/job/22717240878?pr=19#step:4:486)

### Author/Contributor

- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer

- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Review by zkoppert — APPROVED** [review]
✨ 🚢

**Comment by zkoppert** [comment]
@jmeridth Are these linting errors with isort something that V6 of the super linter looks at differently?

**Comment by jmeridth** [comment]
updated super-linter to v6

https://butt.holdings (SFW)

**Comment by jmeridth** [comment]
oK.  Going to fix these new linting issues.

**Comment by jmeridth** [comment]
Even after adding the `install dependencies` to the linting workflow, the super-linter is reporting [unable to find 3rd party package imports](https://github.com/github/cleanowners/actions/runs/8364780191/job/22900957400?pr=38#step:5:365). 🤔

**Comment by jmeridth** [comment]
Ok.  That was painful.  I realized we had this passing in github.com/github/stale-repos.  I borrowed it's `.github/linters/.python-lint` and added the ones we needed.  Having `import-error` included bugs me bug super-linter doesn't handle packages well.  Going to look into that more later.

@zkoppert this is good to merge IMO. and we can close #19  if it doesn't auto-close.

**Comment by zkoppert** [comment]
Generally I think we will catch import errors in our testing so I'm not too stressed about it but it would be nice if this stuff would work as advertised. 😓

**Comment by jmeridth** [comment]
The super-linter arm64 progress seems to be going well. Eventually we'll just run it in a container locally and match the action. Goals and dreams. Goals and dreams.

**Pull request merged**
